openapi: 3.0.0

info:
  title: Authority [Opportunuty]
  description: authorization service for Opportunuty project
  version: '0.2'

servers:
  - url: http://localhost:5000/api/v1/auth/
    description: local development server

paths:
  /register/:
    post:
      description: register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: created
        '400':
          description: registration error

  /login/:
    post:
      description: authorize user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: authoried
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_token: 
                    type: string
  
  /me/:
    get:
      description: getting information about current user
      security: 
        - AuthToken: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


components:
  schemas:
    User:
      type: object
      properties:
        name: 
          type: string
        date_join:
          type: string

  securitySchemes:
    AuthToken:
      type: apiKey
      in: header
      name: Auithorization